# Generated by Django 2.2.3 on 2019-07-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun_name', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Policeoffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_name', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Guns_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun_type', models.CharField(blank=True, max_length=5)),
                ('gun_owner', models.CharField(blank=True, max_length=3)),
                ('gun_age', models.CharField(blank=True, max_length=4)),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navi.Guns')),
            ],
        ),
        migrations.AddField(
            model_name='guns',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navi.Policeoffice'),
        ),
    ]
